name: Calculate Environment Based on Branch
description: Determines the environment (Dev, UAT, Prod) based on the branch name

inputs :
  ref_name:
    required: true
    description: Git branch name (e.g., development, uat, release)
outputs:
  environment:
    description: The determined environment (Dev, UAT, Prod)
    value: ${{ steps.set-env.outputs.env }}
runs:
  using: composite
  steps:
    - name: Determine Environment
      id: set-env
      shell: bash
      run: |
        REF_NAME="${{ inputs.ref_name }}"
        ENV=""

        if [[ "$REF_NAME" == *"development"* || "$REF_NAME" == *"development-"* ]]; then
          ENV="Dev"
        elif [[ "$REF_NAME" == *"uat"* || "$REF_NAME" == *"uat-"* ]]; then
          ENV="UAT"
        elif [[ "$REF_NAME" == *"release"* || "$REF_NAME" == "main" ]]; then
          ENV="Prod"
        else
          echo "❌ Unable to determine environment from branch name: $REF_NAME"
          exit 1
        fi

        echo "Determined environment: $ENV"
        echo "::set-output name=env::$ENV"